/*
 * @Description: t_glasses_p4_driver
 * @Author: LILYGO_L
 * @Date: 2025-08-15 14:29:40
 * @LastEditTime: 2025-12-19 10:31:48
 * @License: GPL 3.0
 */

#pragma once

#include "t_glasses_p4_config.h"
#include "gz030pcc02_driver.h"

#if defined CONFIG_SCREEN_PIXEL_FORMAT_RGB888
#define SCREEN_BITS_PER_PIXEL 24
#define SCREEN_COLOR_RGB_PIXEL_FORMAT LCD_COLOR_PIXEL_FORMAT_RGB888
#define LVGL_COLOR_FORMAT LV_COLOR_FORMAT_RGB888
#else
#error "unknown macro definition, please select the correct macro definition."
#endif

#if defined CONFIG_CAMERA_PIXEL_FORMAT_RGB565
#define CAMERA_BITS_PER_PIXEL 16
#define CAMERA_COLOR_RGB_PIXEL_FORMAT LCD_COLOR_PIXEL_FORMAT_RGB565
#elif defined CONFIG_CAMERA_PIXEL_FORMAT_RGB888
#define CAMERA_BITS_PER_PIXEL 24
#define CAMERA_COLOR_RGB_PIXEL_FORMAT LCD_COLOR_PIXEL_FORMAT_RGB888
#else
#error "unknown macro definition, please select the correct macro definition."
#endif

// SCREEN
#if defined CONFIG_SCREEN_TYPE_GZ030PCC02
#define SCREEN_WIDTH GZ030PCC02_SCREEN_WIDTH
#define SCREEN_HEIGHT GZ030PCC02_SCREEN_HEIGHT
#define SCREEN_MIPI_DSI_DPI_CLK_MHZ GZ030PCC02_SCREEN_MIPI_DSI_DPI_CLK_MHZ
#define SCREEN_MIPI_DSI_HSYNC GZ030PCC02_SCREEN_MIPI_DSI_HSYNC
#define SCREEN_MIPI_DSI_HBP GZ030PCC02_SCREEN_MIPI_DSI_HBP
#define SCREEN_MIPI_DSI_HFP GZ030PCC02_SCREEN_MIPI_DSI_HFP
#define SCREEN_MIPI_DSI_VSYNC GZ030PCC02_SCREEN_MIPI_DSI_VSYNC
#define SCREEN_MIPI_DSI_VBP GZ030PCC02_SCREEN_MIPI_DSI_VBP
#define SCREEN_MIPI_DSI_VFP GZ030PCC02_SCREEN_MIPI_DSI_VFP
#define SCREEN_DATA_LANE_NUM GZ030PCC02_SCREEN_DATA_LANE_NUM
#define SCREEN_LANE_BIT_RATE_MBPS GZ030PCC02_SCREEN_LANE_BIT_RATE_MBPS
#else
#error "unknown macro definition, please select the correct macro definition."
#endif
