/*
 * @Description: t_display_p4_air_driver
 * @Author: LILYGO_L
 * @Date: 2026-01-22 09:15:30
 * @LastEditTime: 2026-01-26 09:57:52
 * @License: GPL 3.0
 */


#pragma once

#include "t_display_p4_air_config.h"
#include "esp32p4_driver.h"

// #if defined CONFIG_SCREEN_PIXEL_FORMAT_RGB888
// #define SCREEN_BITS_PER_PIXEL 24
// #define SCREEN_COLOR_RGB_PIXEL_FORMAT LCD_COLOR_PIXEL_FORMAT_RGB888
// #define LVGL_COLOR_FORMAT LV_COLOR_FORMAT_RGB888
// #else
// #error "no macro definition is set"
// #endif

// #if defined CONFIG_CAMERA_PIXEL_FORMAT_RGB565
// #define CAMERA_BITS_PER_PIXEL 16
// #define CAMERA_COLOR_RGB_PIXEL_FORMAT LCD_COLOR_PIXEL_FORMAT_RGB565
// #elif defined CONFIG_CAMERA_PIXEL_FORMAT_RGB888
// #define CAMERA_BITS_PER_PIXEL 24
// #define CAMERA_COLOR_RGB_PIXEL_FORMAT LCD_COLOR_PIXEL_FORMAT_RGB888
// #else
// #error "no macro definition is set"
// #endif

// // SCREEN
// #if defined CONFIG_SCREEN_TYPE_GZ030PCC02
// #define SCREEN_WIDTH GZ030PCC02_SCREEN_WIDTH
// #define SCREEN_HEIGHT GZ030PCC02_SCREEN_HEIGHT
// #define SCREEN_MIPI_DSI_DPI_CLK_MHZ GZ030PCC02_SCREEN_MIPI_DSI_DPI_CLK_MHZ
// #define SCREEN_MIPI_DSI_HSYNC GZ030PCC02_SCREEN_MIPI_DSI_HSYNC
// #define SCREEN_MIPI_DSI_HBP GZ030PCC02_SCREEN_MIPI_DSI_HBP
// #define SCREEN_MIPI_DSI_HFP GZ030PCC02_SCREEN_MIPI_DSI_HFP
// #define SCREEN_MIPI_DSI_VSYNC GZ030PCC02_SCREEN_MIPI_DSI_VSYNC
// #define SCREEN_MIPI_DSI_VBP GZ030PCC02_SCREEN_MIPI_DSI_VBP
// #define SCREEN_MIPI_DSI_VFP GZ030PCC02_SCREEN_MIPI_DSI_VFP
// #define SCREEN_DATA_LANE_NUM GZ030PCC02_SCREEN_DATA_LANE_NUM
// #define SCREEN_LANE_BIT_RATE_MBPS GZ030PCC02_SCREEN_LANE_BIT_RATE_MBPS
// #elif defined CONFIG_SCREEN_TYPE_ICN6211_ECX336CN
// #define SCREEN_WIDTH ECX336CN_WIDTH
// #define SCREEN_HEIGHT ECX336CN_HEIGHT
// #define SCREEN_MIPI_DSI_DPI_CLK_MHZ ICN6211_SCREEN_MIPI_DSI_DPI_CLK_MHZ
// #define SCREEN_MIPI_DSI_HSYNC ICN6211_SCREEN_MIPI_DSI_HSYNC
// #define SCREEN_MIPI_DSI_HBP ICN6211_SCREEN_MIPI_DSI_HBP
// #define SCREEN_MIPI_DSI_HFP ICN6211_SCREEN_MIPI_DSI_HFP
// #define SCREEN_MIPI_DSI_VSYNC ICN6211_SCREEN_MIPI_DSI_VSYNC
// #define SCREEN_MIPI_DSI_VBP ICN6211_SCREEN_MIPI_DSI_VBP
// #define SCREEN_MIPI_DSI_VFP ICN6211_SCREEN_MIPI_DSI_VFP
// #define SCREEN_DATA_LANE_NUM ICN6211_SCREEN_DATA_LANE_NUM
// #define SCREEN_LANE_BIT_RATE_MBPS ICN6211_SCREEN_LANE_BIT_RATE_MBPS
// #else
// #error "no macro definition is set"
// #endif


