/*
 * @Description: t_display_p4_air_driver
 * @Author: LILYGO_L
 * @Date: 2026-01-22 09:15:30
 * @LastEditTime: 2026-03-23 09:10:41
 * @License: GPL 3.0
 */

#pragma once

#include "esp32p4_driver.h"

#if defined CONFIG_BOARD_TYPE_T_DISPLAY_P4
#include "t_display_p4_config.h"

#define SCREEN_ROTATION_DIRECTION 0
#elif defined CONFIG_BOARD_TYPE_T_DISPLAY_P4_KEYBOARD
#include "t_display_p4_keyboard_config.h"

#define SCREEN_ROTATION_DIRECTION 90
#else
#error "no macro definition is set"
#endif

#if defined CONFIG_SCREEN_PIXEL_FORMAT_RGB565
#define SCREEN_BITS_PER_PIXEL 16
#elif defined CONFIG_SCREEN_PIXEL_FORMAT_RGB888
#define SCREEN_BITS_PER_PIXEL 24
#else
#error "no macro definition is set"
#endif

#if defined CONFIG_CAMERA_PIXEL_FORMAT_RGB565
#define CAMERA_BITS_PER_PIXEL 16
#elif defined CONFIG_CAMERA_PIXEL_FORMAT_RGB888
#define CAMERA_BITS_PER_PIXEL 24
#else
#error "no macro definition is set"
#endif

// SCREEN
#if defined CONFIG_SCREEN_TYPE_HI8561
#define SCREEN_WIDTH HI8561_SCREEN_WIDTH
#define SCREEN_HEIGHT HI8561_SCREEN_HEIGHT
#define SCREEN_MIPI_DSI_DPI_CLK_MHZ HI8561_SCREEN_MIPI_DSI_DPI_CLK_MHZ
#define SCREEN_MIPI_DSI_HSYNC HI8561_SCREEN_MIPI_DSI_HSYNC
#define SCREEN_MIPI_DSI_HBP HI8561_SCREEN_MIPI_DSI_HBP
#define SCREEN_MIPI_DSI_HFP HI8561_SCREEN_MIPI_DSI_HFP
#define SCREEN_MIPI_DSI_VSYNC HI8561_SCREEN_MIPI_DSI_VSYNC
#define SCREEN_MIPI_DSI_VBP HI8561_SCREEN_MIPI_DSI_VBP
#define SCREEN_MIPI_DSI_VFP HI8561_SCREEN_MIPI_DSI_VFP
#define SCREEN_DATA_LANE_NUM HI8561_SCREEN_DATA_LANE_NUM
#define SCREEN_LANE_BIT_RATE_MBPS HI8561_SCREEN_LANE_BIT_RATE_MBPS

#elif defined CONFIG_SCREEN_TYPE_RM69A10
#define SCREEN_WIDTH RM69A10_SCREEN_WIDTH
#define SCREEN_HEIGHT RM69A10_SCREEN_HEIGHT
#define SCREEN_MIPI_DSI_DPI_CLK_MHZ RM69A10_SCREEN_MIPI_DSI_DPI_CLK_MHZ
#define SCREEN_MIPI_DSI_HSYNC RM69A10_SCREEN_MIPI_DSI_HSYNC
#define SCREEN_MIPI_DSI_HBP RM69A10_SCREEN_MIPI_DSI_HBP
#define SCREEN_MIPI_DSI_HFP RM69A10_SCREEN_MIPI_DSI_HFP
#define SCREEN_MIPI_DSI_VSYNC RM69A10_SCREEN_MIPI_DSI_VSYNC
#define SCREEN_MIPI_DSI_VBP RM69A10_SCREEN_MIPI_DSI_VBP
#define SCREEN_MIPI_DSI_VFP RM69A10_SCREEN_MIPI_DSI_VFP
#define SCREEN_DATA_LANE_NUM RM69A10_SCREEN_DATA_LANE_NUM
#define SCREEN_LANE_BIT_RATE_MBPS RM69A10_SCREEN_LANE_BIT_RATE_MBPS

#else
#error "no macro definition is set"
#endif

namespace Lilygo_Device_Driver
{
    bool Spiffs_Init(const char *base_path, esp_vfs_spiffs_conf_t &spiffs_conf);

    bool Sdmmc_Init(const char *base_path, int max_freq_khz = SDMMC_FREQ_DEFAULT);

    bool Sdspi_Init(const char *base_path, spi_host_device_t host_id, int max_freq_khz = SDMMC_FREQ_DEFAULT);
}
