/*
 * @Description: t_glasses_p4_driver
 * @Author: LILYGO_L
 * @Date: 2025-08-15 14:29:40
 * @LastEditTime: 2026-04-16 15:02:51
 * @License: GPL 3.0
 */

#pragma once

#include "esp32p4_driver.h"
#include "t_glasses_p4_config.h"

#if defined(CONFIG_SCREEN_PIXEL_FORMAT_RGB888)
#define SCREEN_BITS_PER_PIXEL 24
#else
#error "Missing required macro definition."
#endif

#if defined(CONFIG_CAMERA_PIXEL_FORMAT_RGB565)
#define CAMERA_BITS_PER_PIXEL 16
#elif defined(CONFIG_CAMERA_PIXEL_FORMAT_RGB888)
#define CAMERA_BITS_PER_PIXEL 24
#else
#error "Missing required macro definition."
#endif

// SCREEN
#if defined(CONFIG_SCREEN_TYPE_GZ030PCC02)
#define SCREEN_WIDTH GZ030PCC02_SCREEN_WIDTH
#define SCREEN_HEIGHT GZ030PCC02_SCREEN_HEIGHT
#define SCREEN_MIPI_DSI_DPI_CLK_MHZ GZ030PCC02_SCREEN_MIPI_DSI_DPI_CLK_MHZ
#define SCREEN_MIPI_DSI_HSYNC GZ030PCC02_SCREEN_MIPI_DSI_HSYNC
#define SCREEN_MIPI_DSI_HBP GZ030PCC02_SCREEN_MIPI_DSI_HBP
#define SCREEN_MIPI_DSI_HFP GZ030PCC02_SCREEN_MIPI_DSI_HFP
#define SCREEN_MIPI_DSI_VSYNC GZ030PCC02_SCREEN_MIPI_DSI_VSYNC
#define SCREEN_MIPI_DSI_VBP GZ030PCC02_SCREEN_MIPI_DSI_VBP
#define SCREEN_MIPI_DSI_VFP GZ030PCC02_SCREEN_MIPI_DSI_VFP
#define SCREEN_DATA_LANE_NUM GZ030PCC02_SCREEN_DATA_LANE_NUM
#define SCREEN_LANE_BIT_RATE_MBPS GZ030PCC02_SCREEN_LANE_BIT_RATE_MBPS
#elif defined(CONFIG_SCREEN_TYPE_ICN6211_ECX336CN)
#define SCREEN_WIDTH ECX336CN_WIDTH
#define SCREEN_HEIGHT ECX336CN_HEIGHT
#define SCREEN_MIPI_DSI_DPI_CLK_MHZ ICN6211_SCREEN_MIPI_DSI_DPI_CLK_MHZ
#define SCREEN_MIPI_DSI_HSYNC ICN6211_SCREEN_MIPI_DSI_HSYNC
#define SCREEN_MIPI_DSI_HBP ICN6211_SCREEN_MIPI_DSI_HBP
#define SCREEN_MIPI_DSI_HFP ICN6211_SCREEN_MIPI_DSI_HFP
#define SCREEN_MIPI_DSI_VSYNC ICN6211_SCREEN_MIPI_DSI_VSYNC
#define SCREEN_MIPI_DSI_VBP ICN6211_SCREEN_MIPI_DSI_VBP
#define SCREEN_MIPI_DSI_VFP ICN6211_SCREEN_MIPI_DSI_VFP
#define SCREEN_DATA_LANE_NUM ICN6211_SCREEN_DATA_LANE_NUM
#define SCREEN_LANE_BIT_RATE_MBPS ICN6211_SCREEN_LANE_BIT_RATE_MBPS
#elif defined(CONFIG_SCREEN_TYPE_S023MSAFJF10111E1)
#define SCREEN_WIDTH S023MSAFJF10111E1_SCREEN_WIDTH
#define SCREEN_HEIGHT S023MSAFJF10111E1_SCREEN_HEIGHT
#define SCREEN_MIPI_DSI_DPI_CLK_MHZ \
  S023MSAFJF10111E1_SCREEN_MIPI_DSI_DPI_CLK_MHZ
#define SCREEN_MIPI_DSI_HSYNC S023MSAFJF10111E1_SCREEN_MIPI_DSI_HSYNC
#define SCREEN_MIPI_DSI_HBP S023MSAFJF10111E1_SCREEN_MIPI_DSI_HBP
#define SCREEN_MIPI_DSI_HFP S023MSAFJF10111E1_SCREEN_MIPI_DSI_HFP
#define SCREEN_MIPI_DSI_VSYNC S023MSAFJF10111E1_SCREEN_MIPI_DSI_VSYNC
#define SCREEN_MIPI_DSI_VBP S023MSAFJF10111E1_SCREEN_MIPI_DSI_VBP
#define SCREEN_MIPI_DSI_VFP S023MSAFJF10111E1_SCREEN_MIPI_DSI_VFP
#define SCREEN_DATA_LANE_NUM S023MSAFJF10111E1_SCREEN_DATA_LANE_NUM
#define SCREEN_LANE_BIT_RATE_MBPS S023MSAFJF10111E1_SCREEN_LANE_BIT_RATE_MBPS
#else
#error "Missing required macro definition."
#endif

namespace lilygo_device_driver {
bool InitSdmmc(const char* base_path, int max_freq_khz = SDMMC_FREQ_DEFAULT);

bool InitSdspi(const char* base_path, spi_host_device_t host_id,
    int max_freq_khz = SDMMC_FREQ_DEFAULT);
}  // namespace lilygo_device_driver
